### ISSUE TITLE
Was ist mit der History in Patient - Detail View??

### ISSUE THREAD

**Issue by dbismor** [MartinLind/HMS#10]

**Comment by martinwichary** [comment]
Ist erledigt.
Admin, Arzt und Pfleger kann jetzt über Patienten --> Details --> Historie sich die Patientenhistorie anzeigen lassen.
Da sind alle LocasCases drin, die dem ausgewählten Patienten hzugeordnet sind. Also die, die aktiv sind (laufen noch) und auch die die inactive sind (also vergangene LocalCases)
