### ISSUE TITLE
Arzt --> Behandlung --> Edit --> Diagnose Doppelt!

### ISSUE THREAD

**Issue by martinwichary** [MartinLind/HMS#21]

**Comment by dbismor** [comment]
Hab ich grad mal rein geschaut.
Da war ein doppeltes feld für Diagnosis, habe ich gelöscht... aber das Problem besteht immer noch?!
Das heißt wohl es wird irgendwie dynamisch erzeugt? o.O

Müssen wir später noch mal drauf gucken zusammen vllt ^^

**Comment by dbismor** [comment]
Also es ist nun folgendes Problem:

Wenn man so auf bearbeiten geht, etwas ändert und speichert ist alles gut, wenn man aber dann direkt noch mal auf die gleiche Behandlung geht mit bearbeiten, dann wird das Layout überschrieben oder so?!
Weil dann fehlen die form-controls unten bei Raum und User, und diese doppelte diagnose ist wieder drin ^^

**Comment by dbismor** [comment]
ok doch jetzt gefixed, bekomme keinen fehler mehr =)
