### ISSUE TITLE
Patienten aufnehmen

### ISSUE THREAD

**Issue by martinwichary** [MartinLind/HMS#23]
Geht bisher so:
Patient suchen
Bearbeiten
Häckchen bei isactive setzen
Speichern

amk, das geht noch schöner

**Comment by dbismor** [comment]
Das ist so, wenn man vergessen hat bei einem Patienten(der noch NICHT in der Kartei war) den Hacken bei isactive zu setzen. Dann muss man den Patienten erst suchen und dann aufnehmen.

Oder genau dann wenn dieser bereits einmal entlassen wurde x)

habe ich gerade erst verstanden wie du das meintest ^^ 
hast du mal getestet, wenn eine Person mit den gleichen Daten 2 mal erfasst wird, was dann passiert?
Sollte ja nicht möglich sein x)

oder sprechen wir morgen x)

**Comment by dbismor** [comment]
Wenn ein Patient aufgenommen werden soll, dann soll nach dem Button erst eine Maske kommen in welcher ein Raum zugewiesen wird und erst danach kommt die Bestätigung.
