### ISSUE TITLE
Behandlungen edit

### ISSUE THREAD

**Issue by martinwichary** [MartinLind/HMS#3]
Room und User werden noch nicht gespeichert. (beim edit)

**Comment by dbismor** [comment]
wenn man eine behandlung bearbeiten will dann wird der zugeteilte raum nicht mehr angezeigt und auch nicht mehr der zugeordnete Arzt, nach abbrechen stehen die aber wieder in der liste

**Comment by dbismor** [comment]
Hatten das Problem gleich doppelt drin x)

**Comment by dbismor** [comment]
Fixed by martin
