### ISSUE TITLE
Dokumentation und Bedoenungsanleitung LAN AMK!

### ISSUE THREAD

**Issue by dbismor** [MartinLind/HMS#8]
Wir brauchen bis ende nächster Woche diese sachen.. leider will schreibarbeit aber muss getan werden..! so Ladys =D... pls do it

**Comment by martinwichary** [comment]
Vorschlag für die Gliederung der Bedienungsanleitung:
1. Inbetriebnahme (wie es aussieht wenn man sich als erstes Einloggt, das man zunächst User, Räume etc. anlegen muss
2.Aus sicht vom Admin
3.aus sicht vom Arzt
etc.

**Comment by Plonka1988** [comment]
Die Dokumentation mach ich schon, hab das auch mit Kempfle durchgesprochen. Bedienungsanleitung guck ich mir am Wochenende dann an, so grundsätzlich finde ich die Gliederung in Ordnung. 

p.s: Denkt dran eure Namen zu kommentieren :)

**Comment by dbismor** [comment]
läuft :D
